### ISSUE TITLE
Isolate everything into a namespace

### ISSUE THREAD

**Issue by andersfylling** [jniemann66/juddperft#8]
I was thinking about forking this and writing another way to verify move generations. But in order to so, I need to import everything into my own project, as an external. But since there aren't namespaces covering globals and functions, this can cause an issue.

Could you isolate everything into a juddperft namespace of some sort?

**Comment by jniemann66** [comment]
Yeah - that's done. You see how nice I am ? I did all that tedious work just for you :-)
It's all wrapped in the juddperft {} namespace now. 
Have a look at main() to see how to start it up. Should be pretty easy.
